# Generated by Django 5.2.17 on 2026-08-06 20:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tienda.models.imagen
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CostoEnvioZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100, unique=True)),
                ('costo_domicilio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_retiro_local', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Costo de Envío por Zona',
                'verbose_name_plural': 'Costos de Envío por Zona',
                'ordering': ['ciudad'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_secuencial', models.CharField(editable=False, max_length=20, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=15, max_digits=4)),
                ('iva_valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('GENERADA', 'Generada'), ('AUTORIZADA', 'Autorizada SRI'), ('ANULADA', 'Anulada')], default='GENERADA', max_length=15)),
                ('clave_acceso_sri', models.CharField(blank=True, max_length=49)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-generada_en'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas/')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text='Ej: 38, 39, 40...', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'ordering': ['valor'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('CONTADOR', 'Contador'), ('VENDEDOR', 'Vendedor'), ('CLIENTE', 'Usuario normal')], default='CLIENTE', max_length=20)),
                ('cedula', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion_referencial', models.CharField(blank=True, help_text='Dirección de referencia del registro; la dirección exacta se pide en cada compra vía Google Maps', max_length=255)),
                ('doble_factor_activo', models.BooleanField(default=False)),
                ('ultima_ip_conocida', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='ImagenAdjunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=tienda.models.imagen._ruta_imagen)),
                ('object_id', models.PositiveIntegerField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['orden', 'creada_en'],
            },
        ),
        migrations.CreateModel(
            name='LibroVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cerrado', models.BooleanField(default=False)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Libro de Ventas',
                'verbose_name_plural': 'Libros de Ventas',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='LiquidacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_anio', models.PositiveIntegerField()),
                ('periodo_mes', models.PositiveSmallIntegerField()),
                ('total_pares', models.PositiveIntegerField(default=0)),
                ('total_comisiones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes_comision/%Y/%m/')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('marcada_pagada_por', models.ForeignKey(blank=True, limit_choices_to={'rol': 'CONTADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_marcadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación Mensual',
                'verbose_name_plural': 'Liquidaciones Mensuales',
                'ordering': ['-periodo_anio', '-periodo_mes'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='tienda.factura')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOLICITUD_COMPRA', 'Compra solicitada'), ('COMPROBANTE_RECIBIDO', 'Comprobante recibido'), ('PAGO_VERIFICADO', 'Pago verificado'), ('PAGO_RECHAZADO', 'Pago rechazado'), ('PEDIDO_ENVIADO', 'Pedido enviado'), ('PEDIDO_ENTREGADO', 'Pedido entregado'), ('COMISION_PAGADA', 'Comisión pagada'), ('PROMOCION', 'Promoción'), ('RECUPERAR_PASSWORD', 'Recuperación de contraseña'), ('ALERTA_SEGURIDAD', 'Alerta de seguridad')], max_length=25)),
                ('asunto', models.CharField(max_length=150)),
                ('mensaje_corto', models.CharField(max_length=255)),
                ('correo_enviado', models.BooleanField(default=False)),
                ('leida', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(choices=[('DOMICILIO', 'Entrega a domicilio'), ('RETIRO_LOCAL', 'Retiro en local')], default='DOMICILIO', max_length=20)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_envio_definido', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Compra solicitada'), ('CONTACTADO', 'Cliente contactado'), ('PAGO_SUBIDO', 'Comprobante subido'), ('PAGO_VERIFICADO', 'Pago verificado'), ('PAGO_RECHAZADO', 'Pago rechazado'), ('EN_PREPARACION', 'En preparación'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado y confirmado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('numero_guia', models.CharField(blank=True, help_text='Código informativo enviado por correo, sin integración de paquetería', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(help_text='Obligatorio: requisito para que se le pueda pagar la comisión', limit_choices_to={'rol': 'VENDEDOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_como_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeChatPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('es_confirmacion_entrega', models.BooleanField(default=False)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat de Pedido',
                'verbose_name_plural': 'Mensajes de Chat de Pedido',
                'ordering': ['enviado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_realizados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Pedido',
                'verbose_name_plural': 'Historial de Estados de Pedido',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='tienda.pedido'),
        ),
        migrations.CreateModel(
            name='DireccionEnvioPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_formateada', models.CharField(max_length=255)),
                ('referencia_adicional', models.CharField(blank=True, help_text='Ej: casa azul, junto a la tienda X', max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('place_id', models.CharField(blank=True, max_length=150)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_envio', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Dirección de Envío',
                'verbose_name_plural': 'Direcciones de Envío',
            },
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='comprobantes_pago/%Y/%m/')),
                ('banco_origen', models.CharField(blank=True, max_length=100)),
                ('numero_referencia', models.CharField(blank=True, max_length=50)),
                ('monto_declarado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de verificación'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_verificados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante_pago', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
            },
        ),
        migrations.CreateModel(
            name='ComisionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pares', models.PositiveIntegerField()),
                ('monto_por_par', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LIQUIDADA', 'Liquidada')], default='PENDIENTE', max_length=15)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('confirmada_por', models.ForeignKey(help_text='Contador que confirmó la entrega y disparó esta comisión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to=settings.AUTH_USER_MODEL)),
                ('liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones', to='tienda.liquidacionmensual')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comision', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Comisión de Venta',
                'verbose_name_plural': 'Comisiones de Venta',
            },
        ),
        migrations.CreateModel(
            name='PerfilContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_autorizacion_sri', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_contador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Contador',
                'verbose_name_plural': 'Perfiles de Contador',
            },
        ),
        migrations.CreateModel(
            name='PerfilVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vendedor', models.CharField(editable=False, max_length=12, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=20)),
                ('numero_cuenta', models.CharField(blank=True, max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Vendedor',
                'verbose_name_plural': 'Perfiles de Vendedor',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('calidad', models.CharField(choices=[('ORIGINAL', 'Original'), ('PRIMERA_CLASE', 'Primera clase'), ('SEGUNDA_CLASE', 'Segunda clase')], default='ORIGINAL', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='tienda.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tienda.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_promocional', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReporteSRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes_sri/%Y/')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('libro_ventas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_sri', to='tienda.libroventas')),
            ],
            options={
                'verbose_name': 'Reporte SRI',
                'verbose_name_plural': 'Reportes SRI',
            },
        ),
        migrations.CreateModel(
            name='RetencionImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_retenido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_sri', models.CharField(blank=True, max_length=20)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones', to='tienda.factura')),
            ],
            options={
                'verbose_name': 'Retención de Impuesto',
                'verbose_name_plural': 'Retenciones de Impuesto',
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='tienda.producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='tienda.talla')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.carrito')),
                ('variante_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.varianteproducto')),
            ],
            options={
                'verbose_name': 'Ítem de Carrito',
                'verbose_name_plural': 'Ítems de Carrito',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.pedido')),
                ('variante_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.varianteproducto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='tienda_usua_rol_afe9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['cedula'], name='tienda_usua_cedula_b58cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenadjunta',
            index=models.Index(fields=['content_type', 'object_id'], name='tienda_imag_content_3d575b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='liquidacionmensual',
            unique_together={('vendedor', 'periodo_anio', 'periodo_mes')},
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='tienda_pedi_estado_9912bc_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario'], name='tienda_pedi_usuario_ad3b01_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['vendedor'], name='tienda_pedi_vendedo_41dd00_idx'),
        ),
        migrations.AddIndex(
            model_name='comisionventa',
            index=models.Index(fields=['vendedor', 'estado'], name='tienda_comi_vendedo_5b01fa_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['marca'], name='tienda_prod_marca_i_3dc222_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='tienda_prod_activo_5eda87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='varianteproducto',
            unique_together={('producto', 'talla')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'variante_producto')},
        ),
    ]
