# Generated by Django 5.2 on 2026-08-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajechatpedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='mensajechatpedido',
            name='remitente',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='tienda_usua_cedula_b58cd5_idx',
        ),
        migrations.RemoveField(
            model_name='direccionenviopedido',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='direccionenviopedido',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='direccionenviopedido',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cedula',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion_referencial',
            field=models.CharField(blank=True, help_text='Dirección de referencia del registro; la dirección exacta se pide en cada compra.', max_length=255),
        ),
        migrations.DeleteModel(
            name='MensajeChatPedido',
        ),
    ]
