# Generated by Django 5.2 on 2026-08-06 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_mensajechatpedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('CARRITO', 'Carrito'), ('PENDIENTE_DE_PAGO', 'Pendiente de pago'), ('COMPROBANTE_ENVIADO', 'Comprobante enviado'), ('PAGO_EN_REVISION', 'Pago en revisión'), ('PAGO_APROBADO', 'Pago aprobado'), ('PAGO_RECHAZADO', 'Pago rechazado'), ('PREPARANDO_PEDIDO', 'Preparando pedido'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Venta finalizada / Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_DE_PAGO', max_length=25),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_guia',
            field=models.CharField(blank=True, help_text='Código informativo enviado por correo', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Vendedor asignado. Si es nulo ("Ningún vendedor"), no genera comisión.', limit_choices_to={'rol': 'VENDEDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_como_vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CampanaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('asunto', models.CharField(max_length=200)),
                ('contenido_html', models.TextField(help_text='Contenido HTML o plantilla renderizable')),
                ('segmento', models.CharField(choices=[('TODOS_LOS_CLIENTES', 'Todos los clientes'), ('VENDEDORES', 'Todos los vendedores'), ('CONTADORES', 'Todos los contadores'), ('CLIENTES_CON_COMPRAS', 'Clientes con compras registradas'), ('CLIENTES_SIN_COMPRAS', 'Clientes sin compras registradas')], default='TODOS_LOS_CLIENTES', max_length=30)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROGRAMADO', 'Programado'), ('ENVIANDO', 'Enviando'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='BORRADOR', max_length=20)),
                ('programado_para', models.DateTimeField(blank=True, null=True)),
                ('total_destinatarios', models.PositiveIntegerField(default=0)),
                ('total_enviados', models.PositiveIntegerField(default=0)),
                ('total_fallidos', models.PositiveIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña de Email',
                'verbose_name_plural': 'Campañas de Email',
                'ordering': ['-creada_en'],
            },
        ),
    ]
