# Generated by Django 5.2.17 on 2026-08-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_pedido_estado_alter_pedido_numero_guia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único del producto para búsquedas internas y del front.', max_length=60, null=True, unique=True),
        ),
    ]
