# Generated by Django 5.2 on 2026-08-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_categoria_imagen_producto_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='calidad',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('PRIMERA_CLASE', 'Full Quality'), ('SEGUNDA_CLASE', 'Calidad 1.1 Plus')], default='ORIGINAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único del producto; si no se envía, se genera automáticamente.', max_length=60, null=True, unique=True),
        ),
    ]
