# Generated by Django 5.2 on 2026-08-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_producto_calidad_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianteproducto',
            name='stock',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
