# Generated by Django 5.2.17 on 2026-08-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_varianteproducto_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccionenviopedido',
            options={'verbose_name': 'Direccion de Envio', 'verbose_name_plural': 'Direcciones de Envio'},
        ),
        migrations.AddField(
            model_name='direccionenviopedido',
            name='provincia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='direccionenviopedido',
            name='telefono_contacto',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='direccionenviopedido',
            name='referencia_adicional',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
