# Generated by Django 5.2.17 on 2026-09-08 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_add_provincia_telefono_to_direccion_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaNotificacionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título llamativo de la notificación', max_length=120)),
                ('cuerpo', models.TextField(help_text='Mensaje principal de la notificación', max_length=500)),
                ('icono_url', models.URLField(blank=True, default='', help_text='URL del icono (ej. logo o zapatilla)', max_length=500)),
                ('imagen_url', models.URLField(blank=True, default='', help_text='Banner o foto grande desplegable', max_length=500)),
                ('url_destino', models.CharField(default='/', help_text='Ruta o URL que se abrirá al dar clic', max_length=300)),
                ('badge_url', models.URLField(blank=True, default='', help_text='Insignia pequeña de la barra', max_length=500)),
                ('sonido_activo', models.BooleanField(default=True, help_text='Reprodur sonido de notificación')),
                ('vibracion_activa', models.BooleanField(default=True, help_text='Vibrar en teléfonos móviles')),
                ('segmento', models.CharField(choices=[('TODOS', 'Todos los dispositivos suscritos'), ('CLIENTES', 'Solo Clientes'), ('VENDEDORES', 'Solo Vendedores'), ('ESPECIFICOS', 'Usuarios específicos seleccionados')], default='TODOS', max_length=20)),
                ('total_enviados', models.IntegerField(default=0)),
                ('total_exitosos', models.IntegerField(default=0)),
                ('total_fallidos', models.IntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_push_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuarios_especificos', models.ManyToManyField(blank=True, help_text='Aplica si el segmento es Usuarios Específicos', related_name='campanas_push_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña Push Personalizada',
                'verbose_name_plural': 'Campañas Push Personalizadas',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='URL de endpoint Push generada por el navegador', max_length=700, unique=True)),
                ('p256dh', models.CharField(help_text='Llave pública cliente p256dh', max_length=255)),
                ('auth', models.CharField(help_text='Secreto de autenticación cliente auth', max_length=255)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario asociado a la suscripción. Puede ser nulo para visitantes/invitados.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción Push',
                'verbose_name_plural': 'Suscripciones Push',
                'ordering': ['-ultima_actividad'],
            },
        ),
    ]
