# Generated by Django 5.2.17 on 2026-10-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_campananotificacionpush_suscripcionpush'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAlmacenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255, unique=True)),
                ('datos', models.BinaryField()),
                ('content_type', models.CharField(default='image/webp', max_length=100)),
                ('tamano_bytes', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Archivo Almacenado',
                'verbose_name_plural': 'Archivos Almacenados',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
