name: Deploy Backend to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull changes & Restart Backend on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/drip_diamond_api
            git pull origin main
            
            if [ -d "venv" ]; then
                source venv/bin/activate
            elif [ -d "env" ]; then
                source env/bin/activate
            elif [ -d ".venv" ]; then
                source .venv/bin/activate
            fi
            
            pip install -r requirements.txt
            python3 manage.py migrate
            python3 manage.py collectstatic --noinput
            
            # Reiniciamos buscando el servicio correcto de systemd en tu servidor
            sudo systemctl restart drip_diamond_api || sudo systemctl restart drip_diamond || sudo systemctl restart gunicorn || true